name: EAS Build

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
        continue-on-error: true

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Build app (preview)
        if: github.event_name == 'pull_request'
        run: |
          eas build --platform all --non-interactive --profile preview --local
        continue-on-error: true

      - name: Build app (production)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          eas build --platform all --non-interactive --profile production --local
        continue-on-error: true